apiVersion: v1
kind: Service
metadata:
  name: kiali-lb
  namespace: istio-system
spec:
  type: LoadBalancer
  selector:
    app: kiali
  ports:
  - port: 20001
    targetPort: 20001
    protocol: TCP
