name: Pipeline CI/CD Microservicios

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Ejecutar Pruebas Unitarias (Despachos)
      run: |
        cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        mvn clean test

    - name: Ejecutar Pruebas Unitarias (Ventas)
      run: |
        cd back-Ventas_SpringBoot/Springboot-API-REST
        mvn clean test

    - name: Login en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build y Push Back-Despachos
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-despachos:latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-despachos:latest

    - name: Build y Push Back-Ventas
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-ventas:latest ./back-Ventas_SpringBoot/Springboot-API-REST
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-ventas:latest

    - name: Build y Push Frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest ./front_despacho
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest
